config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'

  resources :articles do
    resources :comments, except: [:show, :index] 
  end

  post '/get_request_rp', to: 'webhooks#getrequest'
  post '/get_status_rp', to: 'webhooks#getstatus'
  get '/home', to: 'pages#index'
  get '/contact', to: 'pages#contact'
  post '/contactsendform', to: 'pages#contact_send_form'
  get '/all_requests', to: 'webhooks#getallapis'
  get '/all_statuses', to: 'webhooks#getallstatuses'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    MAX_TITLE_LENGTH = 120
    MAX_BODY_LENGTH = 2200

    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { maximum: MAX_TITLE_LENGTH }
    validates :body, length: { maximum: MAX_BODY_LENGTH }
end

app/models/comment.rb
class Comment < ApplicationRecord
  MAX_BODY_LENGTH = 500

  belongs_to :article
  belongs_to :user

  validates :body, presence: true, length: { maximum: MAX_BODY_LENGTH }
end

app/models/status_api.rb
class StatusApi < ApplicationRecord
end

app/models/test_api.rb
class TestApi < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD = /\A      # Must contain 8 or more characters
      (?=.*\d)           # Must contain a digit
      (?=.*[A-Z])        # Must contain an upper case character
      (?=.*[[:^alnum:]]) # Must contain a symbol
  /x

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_save :downcase_email, :capitalize_name

  validates :password,
    format: {
      with: VALID_PASSWORD,
      message: 'must contain digit, upper case and symbol' }
  validates :first_name, :last_name, :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }

  private

  def downcase_email
    self.email = email.downcase
  end

  def capitalize_name
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :current_password])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show] 
    before_action :find_article, except: [:index, :new, :create]
    before_action :correct_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create 
        @article = Article.create(article_params)
        @article.user = current_user
        
        if @article.save
            redirect_to articles_path
        else
            flash[:danger] = @article.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    def destroy 
        if @article.destroy
            redirect_to articles_path
        else
            render @article
        end
    end

    private

    def article_params
        params.require(:article).permit(:title, :body)
    end

    def find_article
        @article = Article.find(params[:id])
    end

    def correct_user
        unless current_user == @article.user
            flash[:danger] = 'You dont have permission!'
            redirect_to @article
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_comment, only: [:edit, :update, :destroy]
    before_action :correct_user, except: [:new, :create, :destroy]

    def new
        @article = Article.find(params[:article_id])
        @comment = @article.comments.build
    end

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            redirect_to article_path(@comment.article)
        else
            flash[:danger] = @comment.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
        @article = @comment.article
    end

    def update
        if @comment.update(comment_params)
            redirect_to article_path(@comment.article)
        else
            flash[:danger] = @comment.errors.full_messages.to_sentence
            render :edit
        end
    end

    def destroy
        if current_user == @comment.user || current_user == @comment.article.user
            @comment.destroy

            redirect_to @comment.article
        else
            flash[:danger] = 'You dont have permission!'
            render @comment.article
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end

    def find_comment
        @comment = Comment.find(params[:id])
    end

    def correct_user
        unless current_user == @comment.user
            flash[:danger] = 'You dont have permission!'
            redirect_to @comment.article
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
    end

    def contact
        @user = User.new
    end

    def contact_send_form
        if user_params.nil?
            render :contact
        else
            UserMailer.contact_email(user_params).deliver
            redirect_to root_path
        end
    end

    private

    def user_params 
        params.require(:user).permit(:first_name, :last_name, :email, :message, :state, :zip)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token
    skip_before_action :authenticate_user!
    def getrequest
        # I should save them to db maybe
        # all params[:]
       
        api = TestApi.new(request_id: params[:request_id],name: params[:name], email_address: params[:email_address], pdf_url: params[:pdf_url])

        if api.save
            render json: {request_id: params[:request_id],name: params[:name], email_address: params[:email_address], pdf_url: params[:pdf_url]}
        end
    end

    def getstatus
        api = StatusApi.new(request_id: params[:request_id], status: params[:status], name: params[:name], email: params[:email_address], profile_link: params[:profile_link])

        if api.save
            render json: {request_id: params[:request_id], status: params[:status], name: params[:name], email: params[:email_address], profile_link: params[:profile_link]}
        end
    end

    def getallapis
        @apis = TestApi.all.order("created_at DESC")
    end

    def getallstatuses
        @apis = StatusApi.all.order("created_at DESC")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_name(user)
        "#{user.first_name} #{user.last_name}"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/articles/_article.html.erb
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card text-center article shadow">
                <div class="card-header">
                    <h4><%= full_name(article.user) %> </h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title"> <strong><%= article.title %></strong></h2>
                    <p class="card-text"> <%= article.body %> </p>
                    <% if local_assigns[:index] %>
                        <%= link_to 'See the full post', article_path(article), class:"btn btn-primary" %>
                    <% else %>
                        <% if current_user == article.user %>
                            <%= link_to 'Delete article', article_path(article), method: :delete, data: {confirm: 'Are u sure?'}, class:"btn btn-danger" %>
                            <%= link_to 'Edit article', edit_article_path(article) , class:"btn btn-primary" %>
                        <% end %>
                        <%= link_to 'Go back to articles', articles_path , class:"btn btn-light" %>
                        <%= link_to 'Comment', new_article_comment_path(article) , class:"btn btn-light" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <%= time_ago_in_words(article.created_at) %>
                </div>
            </div>
            <div class="card pl-3 pt-1 article shadow">
                <% if !local_assigns[:index] %>
                    <h5>Comments</h5>
                    <%= render partial: 'comments/comment', collection: article.comments%>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<div class="container mt-5 mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <h2><%= title %> article</h2>

      <%= form_with model: article, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: 'form-control' %>
          <small id="emailHelp" class="form-text text-muted">Write the title of your article.</small>
        </div>

        <div class="form-group">
          <%= f.label :body %><br />
          <%= f.text_area :body, class: 'form-control' %>
          <small id="emailHelp" class="form-text text-muted">Write the body of your article.</small>
        </div>

        <div class="actions">
            <%= f.submit "#{title} Article", class: "btn btn-primary" %>
            <button class="btn btn-light"> 
                <%= link_to 'Cancel', articles_path %>
            </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article, title: 'Update' %>

app/views/articles/index.html.erb
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-2">
        <%= link_to 'Create Article', new_article_path, class:'btn btn-primary' %>
        </div>
        <div class="col-8">
            <h1> Articles </h1>
        </div>
        
    </div>
</div>
<%= render @articles, index: true %>

app/views/articles/new.html.erb
<%= render 'form', article: @article, title: 'Create' %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/comments/_comment.html.erb
<div class="media">
    <div class="media-body">
        <br>
        <h5 class="mt-0"><%= full_name(comment.user) %>: <span style="color:black;"> <%= comment.body %> </span> </h5>
        <p> 
            <small> 
                <%= time_ago_in_words(comment.created_at) %>
                <span style="margin-left:60%;"> 
                    <% if current_user == comment.user %>
                        <%= link_to 'edit', edit_article_comment_path(comment.article, comment) %>
                    <% end %>
                    <% if current_user == comment.user || current_user == comment.article.user %>
                        <%= link_to 'delete', article_comment_path(comment.article, comment), method: :delete, data: {confirm: 'Are u sure?'} %>
                    <% end %>
                </span>
            </small>
        </p>
    </div>
</div>

app/views/comments/_form.html.erb
<div class="container mt-5 mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <h2><%= title %> comment</h2>

      <%= form_with model: [article, comment], local: true do |f| %>
        <div class="form-group">
          <%= f.label :body %><br />
          <%= f.text_area :body, class: 'form-control' %>
          <small id="emailHelp" class="form-text text-muted"><%= title %> the body of your comment.</small>
        </div>

        <div class="actions">
            <%= f.submit "#{title} Comment", class: "btn btn-primary" %>
            <button class="btn btn-light"> 
                <%= link_to 'Cancel', article_path(comment.article) %>
            </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form', article: @article, comment: @comment, title: 'Edit' %>

app/views/comments/new.html.erb
<%= render 'form', article: @article, comment: @comment, title: 'Create' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietyAp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon_2.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tamma+2&family=Concert+One&family=Do+Hyeon&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= render 'shared/flash' %>
      </div>
    </div>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="image__part bg-light">
    <div class="h-100 container-fluid">

        <%= form_with model: @user, url: '/contactsendform', class: "w-50 needs-validation" do |user_form| %>
        <div class="form-row d-flex">
            <div class="col-md-6 mr-2 mb-3">
            <label for="validationCustom01">First Name</label>
            <%= user_form.text_field :first_name, class: 'form-control', id: 'validationCustom01', placeholder: 'Your firstname...' %>
            <div class="valid-feedback">
                Looks good!
            </div>
            </div>
            <div class="col-md-6 mb-3">
            <label for="validationCustom02">Last Name</label>
            <%= user_form.text_field :last_name, class: 'form-control', id: 'validationCustom02', placeholder: 'Your lastname...' %>
            <div class="valid-feedback">
                Looks good!
            </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col mb-3">
                <label for="validationCustom03">Message</label>
                <%= user_form.text_area :message, class: 'form-control', id: 'validationCustom03', placeholder: 'Message...' %>
                <div class="invalid-feedback">
                    Please provide a valid message.
                </div>
            </div>
            <div class="d-flex">
                <div class="col-md-6 mr-2 mb-3">
                    <label for="validationCustom04">State</label>
                    <%= user_form.text_field :state, class: 'w-100  form-control', id: 'validationCustom04', placeholder: 'State' %>
                    <div class="invalid-feedback">
                        Please select a valid state.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom05">Zip</label>
                    <%= user_form.text_field :zip, class: 'form-control', id: 'validationCustom05', placeholder: 'Zip' %>
                    <div class="invalid-feedback">
                        Please provide a valid zip.
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
            <label class="form-check-label" for="invalidCheck">
                Agree to terms and conditions
            </label>
            <div class="invalid-feedback">
                You must agree before submitting.
            </div>
            </div>
        </div>
        <br>
        <%= user_form.submit "Submit", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/pages/index.html.erb
<style>
   @media only screen and (max-width: 800px) {
        #homepageimage {
            display:none;
        }
    }
</style>
<div class="image__part bg-light">
    <div class="h-100 container-fluid">
        <h2 > Enterprise-grade </h2>
        <h1 style="font-weight: bold;"> Full stack development </h1>
        <%= image_tag 'homepageimage.png', id: "homepageimage", style: "position: absolute;right: 10px;margin-top: -110px;"%>
        <h4 style="color: #6da8db;"> We build solutions for startups, enterprises, and SMEs that help them succeed at the speed of light. </h5>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8"> 
            <br> 
            <br> 
            <p class="text-center" style="opacity:0.7;"> Our service </p>
            <br> 
            <h2 class="text-center" style="font-weight: bold;">Full stack development</h2> 
            <br>
            <h6 class="text-center" style="color: #6da8db;"> We create quality software products that benefit businesses of any size.
            We go beyond technology solution to understand your vision and deliver intuitive, custom-made,
            and customer-centric web and mobile app solutions. </h6>
        </div>
        <div class="col-2"></div>
    </div>

    <div class="row">
        <div class="col-2"> </div>
        <div class="col-8">
            <br>
            <br>
            <div class="d-flex justify-content-center flex-wrap">
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="far fa-gem fa-2x"></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Ruby on Rails Development </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            With the years of experience and result-driven approach in RoR development, we help you leverage Ruby On Rails, a full-stack and
                            modern development framework to create reliable and user-friendly solutions.
                        </p>
                    </div>
                </div>
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="fab fa-shopify fa-2x"></i></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Shopify Development </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            Our focused mindset of delivering rapid, usable, and engaging experience in eCommerce help you achieve desirable results in no time.
                            We craft enhanced ecommerce solutions leveraging our skills and experience into Shopify development.
                        </p>
                    </div>
                </div>
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="fas fa-network-wired fa-2x"></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Full Stack Application Development </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            The web is not limited to just static web pages. Use our full-stack development services to lure your users and deliver 
                            them interactive, modern, and beautiful experiences at affordable costs.
                        </p>
                    </div>
                </div>
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="fab fa-osi fa-2x"></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Open Source Customization </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            Experience with many years of best practices and basic depth knowledge of technology makes us very comfortable for web open source customization and with this, we can save
                            your time to use existing solutions with minimum customization as per need.
                        </p>
                    </div>
                </div>
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="fab fa-cloudversify fa-2x"></i></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Cloud Services </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            We are here to assist you in connecting the world with your best idea of application with many cloud services like Amazon AWS,
                            Google Cloud, Digital Ocean, Heroku, and many more servers in an automated way as per your requirement.
                        </p>
                    </div>
                </div>
                <div class="card m-3 shadow p-3 mb-5 bg-white rounded" style="max-width: 18rem;">
                    <div class="card-header d-flex justify-content-center"><i class="fas fa-chalkboard-teacher fa-2x"></i></div>
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"> <strong> Personal Application Development </strong> </h5>
                        <p class="card-text d-flex justify-content-center">
                            Our professional team and our engineers always looks for individual people who really needs 
                            to have a personal website or for portfolio or for any other reason, always on their side.
                            We create website eben for individuals not just for companies.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2"> </div>
    </div>

    <div class="row bg-light">
        <div class="col-1"></div>
        <div class="col-6 d-flex align-items-center "> 
            <div>
                <br> 
                <br> 
                <p class="text-center" style="opacity:0.7;"> Our vision </p>
                <h2 class="text-center" style="font-weight: bold;">Industries We Serve</h2> 
                <br>
                <h6 class="text-center" style="color: #6da8db;"> You can hardly find a sector where technology hasn’t entered yet.
                No matter what your business model is, we work together to deliver the best experience possible using the latest technologies and tools. We constantly learn and update 
                ourselves with the latest tools and modern mindsets to build web and mobile apps for every domain. </h6>
            </div>
        </div>
        <div class="col-5">
            <div class="d-flex justify-content-center">
                <%= image_tag 'digital.png', width: '80%', class: 'p-5' %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 d-flex"> 
            <div>
                <br> 
                <br> 
                <p class="text-center" style="opacity:0.7;"> Our work </p>
                <h2 class="text-center" style="font-weight: bold;">Client Satisfaction is Our Motto</h2> 
                <br>
                <div class="d-flex justify-content-center flex-wrap">
                    <div class="card m-1 shadow mb-5 bg-white rounded" style="max-width: 25rem;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'pickar.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                    <div class="card m-1 shadow mb-5 bg-white rounded" style="max-width: 25rem;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'seeu.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                    <div class="card m-1 shadow mb-5 bg-white rounded" style="max-width: 25rem; ">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'cooking.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                </div>
                <br>
                <br>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
    <!-- 
    <div class="row bg-light">
        <div class="col-1"></div>
        <div class="col-10">
            <div>
                <br> 
                <br>
                <h1 class="text-center">Technologies that we use</h1> 
                <br>
                <div class="d-flex justify-content-center flex-wrap tech">
                    <div class="card m-1" style="max-width: 10rem; border-radius:50%;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'rubyOn.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                    <div class="card m-1" style="max-width: 10rem; border-radius:50%;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'Angular.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                    <div class="card m-1" style="max-width: 10rem; border-radius:50%;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'Php.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                    <div class="card m-1" style="max-width: 10rem; border-radius:50%;">
                        <div class="card-body d-flex align-items-center">
                            <%= image_tag 'React.png', width: '100%', height: '100%' %>
                        </div>
                    </div>
                </div>
                <br>
                <br>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
    -->
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
    <% if type == 'notice' %>
        <% type = 'warning' %>
    <% else %> 
        <% type = 'danger' %>
    <% end %>
    <div class="alert alert-<%= type %>" role="alert">
        <h6 class="text-center mt-2"> <%= msg %></h6> 
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer bg-dark">
    <div class="bg-primary">
        <div class="container">
            <div class="row py-4 d-flex align-items-center">
                <div class="col-md-12 text-center">
                    <a target="_blank" href="https://www.facebook.com/dietyapp"> <i class="fab fa-facebook-square text-white mr-4"></i> </a>
                    <a target="_blank" href="https://www.linkedin.com/company/dietyap"> <i class="fab fa-linkedin text-white mr-4"></i> </a>
                    <a href="#"> <i class="fab fa-google-plus-square text-white mr-4"></i> </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container text-center text-md-left mt-5">
        <div class="row">
            <div class="col-md-3 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold"> Diety Ap </h6>
                <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width: 125px; height: 2px;">
                <p>DietyAp was established in 2016 with an idea to build
                high performance, scalable and secure web and mobile applications
                with a team of experts who can deliver
                best solutions ever to our clients within the decided timeframe. </p>
            </div>

            <div class="col-md-2 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold"> Quick links </h6>
                <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width: 85px; height: 2px;">
                <ul class="list-unstyled">
                    <li class="my-2"> <%= link_to 'Home', root_path %> </li>
                    <li class="my-2"> <%= link_to 'Contact', contact_path %> </li>
                    <li class="my-2"> <%= link_to 'Blog', articles_path %> </li>
                </ul>
            </div>

            <div class="col-md-3 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold"> Get in Touch </h6>
                <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width: 125px; height: 2px;">
                <h4> Head Office </h4>
                <p> 1612 Npz Stedets, Sofia
                Bulgaria <p>
                <ul class="list-unstyled">
                    <li class="my-2"> <i class="fas fa-envelope"></i> dietyapcontact@gmail.com </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="footer-copyright text-center py-3">
        <p>&copy; Copyright 
            <a href="#">dietyap.com</a>
        </p>
        <p> Designed With <i class="fas fa-heart" style="color: red;"></i> By DietyAp Team </p>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="/">
            <%= image_tag "lougou1.png", width: "190", height: "90", class: "d-inline-block" %>
        </a>
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <%= link_to 'Home', home_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Contact', contact_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Blog', articles_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
                </li>
            <% end %>
        </ul>   
    </div>    
</nav>